---
title: "PCA_Thesis 2"
author: "Ohtake"
date: "2019年9月25日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# パッケージの読み込み
```{r}
library("tidyverse") 
library("readxl") 
library("FactoMineR") # このパッケージでPCA，RDA解析ができます。 
library("factoextra")
library("tidyverse") # データ処理や作図に使う関数はここにある
library("lubridate") # 時間データ処理に使う関数はここ
library("gridExtra")
library("gcookbook")
library("readxl")
library("dplyr")
library("ggsci")
library("nlstools")
library("broom")
```
```{r}
# データの読み込み
data = read_xlsx("主成分分析_190924.xlsx", 
                 sheet = "Raw data_full year",
                 skip = 1,
                 col_names = c("Vmax",
                               "Km",
                               "Vmax/Km",
                               "P uptake",
                               "P demand(max)",
                               "P demand(in situ)",
                               "Growth rate(max)",
                               "Growth rate(in situ)",
                               "Total P contents",
                               "PO4 conc.",
                               "NO3 conc.",
                               "PAR",
                               "Temp.",
                               "Wet Weight")) 
data
d3 = data[, c(-1, -2, -3, -5, -7, -11, -14)]
d3 = d3 %>% drop_na() 
d3

# 欠損値を外す PCAはここであてはめる。 
d3out = PCA(d3, graph = FALSE) 

# PCA細かい情報はここで抽出します。
# まず，主成分に対する各要因の貢献度(Contribution)。 
tmp1 = get_pca_var(d3out) %>% pluck("contrib") %>% 
as_tibble(rownames = "Variable") %>% 
gather("Dim", "Contribution", -Variable) 

# つぎに，主成分に対する各要因の相関係数。 
tmp2 = get_pca_var(d3out) %>% pluck("cor") %>% 
as_tibble(rownames = "Variable") %>% 
gather("Dim", "Correlation", -Variable) 

# この２つの情報を結合して，貢献度の評価をします。
# N要因の貢献度が等しいとき，貢献度は100/Nです。つまり，貢献度が100/N以上のとき，その要因が主成分に強く影響しています。 
d3_x = full_join(tmp1, tmp2) 

# 結合 
N = length(unique(tmp1$Variable)) 

# 要因の数 貢献度の評価はここで行います。 
d3_x = d3_x %>% mutate(C = ifelse(Contribution > 100 / N, "Above average contribution", "Below average contribution")) 

# さらに，主成分分析の図をつくるためのデータをもとめます。 
pcacoord = get_pca_var(d3out) %>% 
  pluck("coord") %>% 
  as_tibble(rownames = "Variable") 
pcacoord = pcacoord %>% 
  mutate(d1 = 1.1*sqrt(Dim.1^2 + Dim.2^2) * sin(atan2(Dim.1, Dim.2)), 
         d2 = 1.1*sqrt(Dim.1^2 + Dim.2^2) * cos(atan2(Dim.1, Dim.2)), 
         d3 = 1.1*sqrt(Dim.3^2 + Dim.4^2) * sin(atan2(Dim.3, Dim.4)), 
         d4 = 1.1*sqrt(Dim.3^2 + Dim.4^2) * cos(atan2(Dim.3, Dim.4)), 
         a1 = atan2(Dim.2, Dim.1), 
         a2 = atan2(Dim.4, Dim.3)) %>% 
  mutate(adj1 = ifelse(abs(a1) > pi/2, a1 - pi, a1), 
         adj2 = ifelse(abs(a2) > pi/2, a2 - pi, a2)) 

# 固有値があれば，主成分がどの程度全体の分散を説明しているかがわかります。 
eval = d3out %>% get_eig()
```

```{r}
cap = "主成分１に対すして，相関の高い順でならべた要因です。 黒丸は貢献度が 100/14 を超えた要因です。 主成分１に貢献する要因は８つあります。"

d3_x %>% filter(str_detect(Dim, "Dim.1")) %>% 
  ggplot(aes(x = reorder(Variable, -Correlation), 
             y = Correlation)) + 
  geom_line(aes(group = 1), 
            linetype = "dotted") + 
  geom_point(aes(shape = C, fill = C), size = 3) + 
  geom_hline(yintercept= 0, linetype = "dashed") + 
  scale_x_discrete("") + 
  scale_y_continuous("Dimension 1", limits = c(-1,1)) + 
  scale_shape_manual(values = c(19, 21)) + 
  scale_fill_manual(values = c("black", "white")) + 
  theme(legend.background=element_blank(), 
        legend.position=c(1,1), 
        legend.justification=c(1,1), 
        legend.title=element_blank()) 

cap = "主成分2に対すして，相関の高い順でならべた要因です。黒丸は貢献度が 100/14 を超えた要因です。 主成分2に貢献する要因は5つあります。"
d3_x %>% filter(str_detect(Dim, "Dim.2")) %>% 
  ggplot(aes(x = reorder(Variable, -Correlation), 
             y = Correlation)) + 
  geom_line(aes(group = 1), 
            linetype = "dotted") + 
  geom_point(aes(shape = C, fill = C), size = 3) + 
  geom_hline(yintercept= 0, linetype = "dashed") + 
  scale_x_discrete("") + 
  scale_y_continuous("Dimension 2", limits = c(-1,1)) + 
  scale_shape_manual(values = c(19, 21)) + 
  scale_fill_manual(values = c("black", "white")) + 
  theme(legend.background=element_blank(), 
        legend.position=c(1,1), 
        legend.justification=c(1,1), 
        legend.title=element_blank()) 

cap = "主成分3に対すして，相関の高い順でならべた要因です。黒丸は貢献度が 100/14 を超えた要因です。 主成分3に貢献する要因は4つあります。"
d3_x %>% filter(str_detect(Dim, "Dim.3")) %>% 
  ggplot(aes(x = reorder(Variable, -Correlation), 
             y = Correlation)) + 
  geom_line(aes(group = 1), 
            linetype = "dotted") + 
  geom_point(aes(shape = C, fill = C), size = 3) + 
  geom_hline(yintercept= 0, linetype = "dashed") + 
  scale_x_discrete("") + 
  scale_y_continuous("Dimension 3", limits = c(-1,1)) + 
  scale_shape_manual(values = c(19, 21)) + 
  scale_fill_manual(values = c("black", "white")) + 
  theme(legend.background=element_blank(), 
        legend.position=c(1,1), 
        legend.justification=c(1,1), 
        legend.title=element_blank()) 

cap = "主成分4に対すして，相関の高い順でならべた要因です。黒丸は貢献度が 100/14 を超えた要因です。 主成分4に貢献する要因は3つあります。"
d3_x %>% filter(str_detect(Dim, "Dim.4")) %>% 
  ggplot(aes(x = reorder(Variable, -Correlation), 
             y = Correlation)) + 
  geom_line(aes(group = 1), 
            linetype = "dotted") + 
  geom_point(aes(shape = C, fill = C), size = 3) + 
  geom_hline(yintercept= 0, linetype = "dashed") + 
  scale_x_discrete("") + 
  scale_y_continuous("Dimension 4", limits = c(-1,1)) + 
  scale_shape_manual(values = c(19, 21)) + 
  scale_fill_manual(values = c("black", "white")) + 
  theme(legend.background=element_blank(), 
        legend.position=c(1,1), 
        legend.justification=c(1,1), 
        legend.title=element_blank()) 
```

```{r}
# 主成分分析の図に，correlationcircleを乗せるための関数です。 
circleFun <- function(center = c(0,0),diameter = 1, npoints = 100){
  r = diameter / 2 
  tt <- seq(0,2*pi,length.out = npoints) 
  xx <- center[1] + r * cos(tt) 
  yy <- center[2] + r * sin(tt) 
  return(tibble(x = xx, y = yy)) 
  }

cap = "The first principal component plane, ここで主成分１と２を座標軸にしています。"
#矢印が円に近いほど，その要因がこの面に強く貢献している。
#つまり，矢印の長さが１のとき，円と重なり，その要因は他の主成分に貢献していない。
#矢印と矢印の間の角度のcos() をとれば，そのペアの相関係数を求められます。"

xlab = str_glue("Dim. 1 ({round(eval[1,2], 1)}%)") 
ylab = str_glue("Dim. 2 ({round(eval[2,2], 1)}%)") 
ggplot(pcacoord) + 
  geom_vline(xintercept=0, linetype = "dashed") + 
  geom_hline(yintercept=0, linetype = "dashed") + 
  geom_segment(aes(x = 0, y = 0, 
                   xend = Dim.1, 
                   yend = Dim.2), 
               arrow=arrow(angle = 20, length = unit(5, "mm"), type="closed")) + 
  geom_text(aes(x = d1, y = d2, label = Variable, 
                angle = 360*adj1/(2*pi)), 
            hjust = 1, 
            data = pcacoord %>% filter(abs(pcacoord$a1) > pi/2)) + 
  geom_text(aes(x = d1, y = d2, label = Variable, 
                angle = 360*adj1/(2*pi)), 
            hjust = 0, 
            data = pcacoord %>% filter(abs(pcacoord$a1) < pi/2)) + 
  geom_path(aes(x = x, y = y), 
            data = circleFun(diameter = 2)) + 
  scale_x_continuous(xlab, limits = c(-1.2, 1.2)) + 
  scale_y_continuous(ylab, limits = c(-1.2, 1.2)) + 
  coord_equal() 

cap = "The third principal component plane, ここで主成分３と４を座標軸にしています。"
#この面の場合，前リンだけ強く貢献しています。

xlab = str_glue("Dim. 3 ({round(eval[3,2], 1)}%)") 
ylab = str_glue("Dim. 4 ({round(eval[4,2], 1)}%)") 
ggplot(pcacoord) + 
  geom_vline(xintercept=0, linetype = "dashed") + 
  geom_hline(yintercept=0, linetype = "dashed") + 
  geom_segment(aes(x = 0, y = 0, 
                   xend = Dim.3, 
                   yend = Dim.4), 
               arrow=arrow(angle = 20, length = unit(5, "mm"), type="closed")) + 
  geom_text(aes(x = d3, y = d4, label = Variable, 
                angle = 360*adj1/(2*pi)), 
            hjust = 1, 
            data = pcacoord %>% filter(abs(pcacoord$a1) > pi/2)) + 
  geom_text(aes(x = d3, y = d4, label = Variable, 
                angle = 360*adj1/(2*pi)),
            hjust = 0,
            data = pcacoord %>% filter(abs(pcacoord$a1) < pi/2)) + 
  geom_path(aes(x = x, y = y),
            data = circleFun(diameter = 2)) + 
  scale_x_continuous(xlab, limits = c(-1.2, 1.2)) + 
  scale_y_continuous(ylab, limits = c(-1.2, 1.2)) + 
  coord_equal() 

cap = "主成分に対する各要因の修正分負荷量 (loading)。最初の５つの主成分だけ示しています。" 
Table_1 = get_pca(d3out) %>% pluck("coord") %>% as_tibble(rownames = "Variable") %>% 
  arrange(desc(Dim.1)) %>% 
  knitr::kable(format = "latex", 
               booktabs = TRUE, digits=4, linesep = "", 
               caption=cap) 
Table_1


cap = "主成分に対する各要因の相関係数 (correlation)。最初の５つの主成分だけ示しています。" 
Table_2 = get_pca(d3out) %>% pluck("cor") %>% as_tibble(rownames = "Variable") %>% 
  arrange(desc(Dim.1)) %>% 
  knitr::kable(format = "latex", 
               booktabs = TRUE, digits=4, 
               linesep = "", caption=cap) 
Table_2

cap = "主成分に対する各要因の貢献度(contribution)。最初の５つの主成分だけ示しています。列の和は１００です。要因が同等に貢献している場合，貢献度"

Table_3 = get_pca(d3out) %>% pluck("contrib") %>% as_tibble(rownames = "Variable") %>% 
  arrange(desc(Dim.1)) %>% 
  knitr::kable(format = "latex", 
               booktabs = TRUE, digits=4, 
               linesep = "", caption=cap)
Table_3
```